### ISSUE TITLE
Compilation Error - `cannot find -lso.5.7.1`

### ISSUE THREAD

**Issue by sneakers-the-rat** [WinterLab-Berlin/LabNet#1]
Hello! Trying to compile the code to run the tests, having trouble compiling. I don't use VSCode, is that required? I installed the dependencies specified in the docs, update to the latest versions, and attempted to compile with cmake and gcc (8.3.0)

Here was the output from CMake:

```
(venv) pi@pilot1:~/git/LabNet $ cmake . 
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SFML 2.5.1 in /usr/lib/arm-linux-gnueabihf/cmake/SFML
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/git/LabNet
```

and here is the stdout from the build process: https://gist.github.com/sneakers-the-rat/6972a68fb5df8dc102c9303e33b8cef3

If it's as simple as using VSCode I can try that, but my pis are all headless so I would have to flash a new image.

I can't really make sense of what the error might be, but in any case when the linker goes to do the linking it's unable to find the file because of a previous build error. Please let me know what i'm doing wrong! Thank you!

**Comment by darki-31** [comment]
Hi,

yes, I think it has to do with the linking against sobjectizer module. LabNet use already 5.7.1 version in the cmake file but the version 5.7.0 is checked out.
So please change in the file “LabNet/CMakeLists.txt” under “target_link_libraries” the “so.5.7.1” to “so.5.7.0”. Then run Cmake and make again. This should fix the problem.
I will also change later which sobjectizer version git checks out.
